In [ ]:
# Cite:
# OBrien, William, 2020, "Time1 dataset (october 26, 2020): demographic, health, and psychological predictors (mindfulness, perceived susceptibility) of COVID-19 PPE use, social distancing, psychological distress, and physical symptoms", https://doi.org/10.7910/DVN/UDHBOB, Harvard Dataverse, V1, UNF:6:NByE2zYH4xRsgUbD8vqE0A== [fileUNF]

In [1]:
import pandas as pd
import numpy as np

In [5]:
# Harvard Dataverse (Time 1 first data set (1 of 2)) 
# Survey Team - William O'Brien
data = pd.read_excel("time1dataset.xlsx")

In [6]:
df = pd.DataFrame(data)

In [7]:
df

,ID_case#,Date,Gender,Age,Occupation,Employment_status_Befor_COVID,Employment_status_After_COVID,Marital_status,Education,Race,...,FFMQdescribemean,Patient_Health_Questionnaire_Total,Quality_of_Life_Total,General_Health_Questionnaire_Negative_Total,Perceived_Vulnerability_to_Disease_Total,Intolerance_of_Uncertainty_Total,Preventive_Action_Taken_Scale_PPEuse_Total,Preventive_Action_Taken_Scale_Avoid_Travel_People_Total,Impact_of_Events_Scale_Total,Number_of_children
0,1,2020-04-09 12:15:43,2,24.0,Account Officer,3,1,1,5,3,...,2.2,10,33,11,44,30,6,10,27,2
1,2,2020-04-09 12:21:26,2,41.0,Customer Care Representative,3,1,4,5,2,...,4.4,7,39,13,45,41,9,20,35,1
2,3,2020-04-09 12:36:29,2,35.0,IT Administrator,1,3,4,5,2,...,3.6,17,30,20,48,49,5,10,38,2
3,4,2020-04-09 12:38:05,1,35.0,Mahnager,3,3,4,6,2,...,3.0,21,35,27,47,54,10,17,75,2
4,5,2020-04-09 12:43:36,1,47.0,research analyst,3,2,5,6,2,...,4.4,2,37,20,44,33,4,19,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,548,2020-04-18 14:06:48,1,29.0,IT,2,3,4,5,2,...,3.2,14,35,21,44,42,8,12,53,2
446,549,2020-04-18 14:10:47,2,26.0,engineer,3,3,4,5,2,...,2.6,0,33,18,45,36,8,12,43,0
447,551,2020-04-18 15:00:24,2,45.0,Marketing,2,3,4,4,2,...,3.0,17,36,23,46,48,9,12,62,0
448,553,2020-04-18 15:20:40,1,28.0,marketing,3,2,4,5,1,...,2.8,22,38,26,44,51,10,16,69,0
449,634,2020-04-24 03:42:26,2,25.0,software developer,3,2,1,5,2,...,3.4,11,30,23,45,41,8,14,56,0

In [8]:
df.isnull().sum()

ID_case#                                                     0
Date                                                         0
Gender                                                       0
Age                                                          1
Occupation                                                   1
Employment_status_Befor_COVID                                0
Employment_status_After_COVID                                0
Marital_status                                               0
Education                                                    0
Race                                                         0
Religion_Protestant                                        366
Religion_Roman_Catholic                                    207
Religion_Mormon                                            448
Religion_Jewish                                            435
Religion_Muslim                                            440
Religion_Buddhist                                          442
Religion_Taoist                                            446
Religion_Hindu                                             443
Religion_Agnostic                                          422
Religion_Atheist                                           425
Religion_Nothing_in_particular                             421
Religion_Something_else                                    431
Religion_12_describe                                         0
Annual_income                                                0
Illnesses                                                    1
Illnesses_2_describe                                         0
Meds                                                         1
Meds_2_describe                                              1
Country                                                      0
State                                                        0
City                                                         1
Accomodation                                                 0
Isolation_yesorno                                            0
Isolation_number_of_days                                   143
Isolation_number_times_leave_per_day                        17
Perceived_susceptibility_COVID                               2
FFMQdescribetotal                                            0
FFMQnonreacttotal                                            0
FFMQnonjudgetotal                                            0
FFMQobservetotal                                             0
FFMQawaretotal                                               0
FFMQtotal                                                    0
FFMQnonjudgemean                                             0
FFMQnonreactmean                                             0
FFMQobservemean                                              0
FFMQawaremean                                                0
FFMQdescribemean                                             0
Patient_Health_Questionnaire_Total                           0
Quality_of_Life_Total                                        0
General_Health_Questionnaire_Negative_Total                  0
Perceived_Vulnerability_to_Disease_Total                     0
Intolerance_of_Uncertainty_Total                             0
Preventive_Action_Taken_Scale_PPEuse_Total                   0
Preventive_Action_Taken_Scale_Avoid_Travel_People_Total      0
Impact_of_Events_Scale_Total                                 0
Number_of_children                                           0
dtype: int64